### ISSUE TITLE
Unsupported Command: blob

### ISSUE THREAD

**Issue by bshimel** [rvaughn/cvs-fast-export#1]
I am running cvs-fast-export on Windows 7 64-bit and I am using git verion 1.9.4.msysgit.2.  When I run cvs-fast-export, I get an error that says "Unsupported command: blob".  If I use the --no-blobs option, then I get an error that branch "refs/head/master" is not legal git branch.

I suspect it has something to do with the CRLF, but I am not sure.  Did you experience anything similar or have any suggestions?

Thanks,
Bruce

**Comment by rvaughn** [comment]
Hi Bruce,
It shouldn't be a CRLF issue, but I'll try it out here and see if I can reproduce it. I wrote this using an earlier version of Git, so it's possible something has changed since then.

What is your source repository? CVSNT?

**Comment by rvaughn** [comment]
Easy repro. Fix coming soon.

**Comment by rvaughn** [comment]
Bruce, you're absolutely right. There's an issue with CRLF in the command stream that git-fast-import doesn't like. I just pushed a change that _may_ work for you. It does not yet work for me, so I will continue working on it tomorrow.

I originally wrote this to run under Linux, so I did not adequately test it under Windows. Sorry about that.
